# Generated by Django 2.1.2 on 2019-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_stk_prc_tr',
            name='day_before_ratio',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
