# Generated by Django 2.1.2 on 2019-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('tweet_string', models.CharField(max_length=280)),
                ('bot_retweet_cnt', models.IntegerField(default=0, null=True)),
                ('reply_to_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('screen_name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('retweets_cnt_for_me', models.IntegerField(null=True)),
                ('my_retweets_cnt', models.IntegerField(null=True)),
                ('favourites_cnt_for_me', models.IntegerField(null=True)),
                ('my_favourites_cnt', models.IntegerField(null=True)),
                ('replies_cnt_for_me', models.IntegerField(null=True)),
                ('my_replies_cnt', models.IntegerField(null=True)),
                ('last_tweet_date', models.DateTimeField(null=True)),
                ('follows_cnt', models.IntegerField(null=True)),
                ('followers_cnt', models.IntegerField(null=True)),
                ('likes_cnt', models.IntegerField(null=True)),
                ('listed_cnt', models.IntegerField(null=True)),
                ('follow_flg', models.BooleanField(default=False)),
                ('follower_flg', models.BooleanField(default=False)),
                ('cmn_follow_cnt', models.IntegerField(null=True)),
                ('cmn_followers_cnt', models.IntegerField(null=True)),
                ('statuses_count', models.IntegerField(null=True)),
            ],
        ),
    ]
