# Generated by Django 2.1.2 on 2019-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('retweets_cnt_for_me', models.IntegerField(null=True)),
                ('my_retweets_cnt', models.IntegerField(null=True)),
                ('likes_cnt_for_me', models.IntegerField(null=True)),
                ('my_likes_cnt', models.IntegerField(null=True)),
                ('replies_cnt_for_me', models.IntegerField(null=True)),
                ('my_replies_cnt', models.IntegerField(null=True)),
                ('last_tweet_date', models.DateTimeField(null=True)),
                ('follows_cnt', models.IntegerField(null=True)),
                ('followers_cnt', models.IntegerField(null=True)),
                ('likes_cnt', models.IntegerField(null=True)),
                ('lists_cnt', models.IntegerField(null=True)),
                ('follow_flg', models.BooleanField(default=True)),
                ('follower_flg', models.BooleanField(default=True)),
                ('cmn_follow_cnt', models.IntegerField(null=True)),
                ('cmn_followers_cnt', models.IntegerField(null=True)),
            ],
        ),
    ]
