# Generated by Django 2.1.2 on 2019-07-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feivs2019AccountManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes_cnt_for_me',
            new_name='favourites_cnt_for_me',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lists_cnt',
            new_name='listed_cnt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='my_likes_cnt',
            new_name='my_favourites_cnt',
        ),
        migrations.AddField(
            model_name='user',
            name='screen_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='statuses_count',
            field=models.IntegerField(null=True),
        ),
    ]
