# Generated by Django 2.1.2 on 2019-07-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feivs2019AccountManager', '0002_auto_20190723_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Users',
        ),
    ]
