# Generated by Django 2.1.2 on 2019-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feivs2019AccountManager', '0002_mytweets_reply_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytweets',
            name='reply_to_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
