# Generated by Django 2.1.2 on 2019-07-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feivs2019AccountManager', '0003_auto_20190724_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
