# Generated by Django 2.1.2 on 2019-07-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feivs2019AccountManager', '0003_auto_20190725_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytweets',
            name='reply_to_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
