# Generated by Django 2.1.1 on 2018-09-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_BLAND_MS',
            fields=[
                ('bland_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('bland_name', models.CharField(max_length=128)),
                ('market_prod_cls', models.CharField(max_length=64)),
                ('sub_industry_cd', models.IntegerField()),
                ('fetch_flg', models.BooleanField(default=True)),
                ('access_url_string', models.URLField(max_length=2083)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_CONDITIONS_MS',
            fields=[
                ('conditions_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('conditions_name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_EXT_CND_CH_TR',
            fields=[
                ('condition_ch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('condition_type', models.CharField(max_length=256)),
                ('threshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_EXT_CND_TR',
            fields=[
                ('condition_no', models.IntegerField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_INDUSTRY_MS',
            fields=[
                ('industry_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_SCALE_MS',
            fields=[
                ('scale_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('scale_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_STATISTIC_MS',
            fields=[
                ('statistic_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('statistic_name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_STK_PRC_TR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_prod_cls', models.CharField(max_length=256)),
                ('current_price', models.FloatField()),
                ('day_before_ratio', models.CharField(max_length=64)),
                ('opening_price', models.FloatField()),
                ('high_orice', models.FloatField()),
                ('low_price', models.FloatField()),
                ('sales_volume', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bland_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_BLAND_MS')),
            ],
        ),
        migrations.CreateModel(
            name='T_TRG_PRM_MS',
            fields=[
                ('trg_prm_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('trg_prm_name', models.CharField(max_length=64)),
                ('find_tag', models.CharField(max_length=64)),
                ('class_string', models.CharField(max_length=128)),
                ('exclude_tags', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_UNIT_MS',
            fields=[
                ('unit_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_ext_cnd_ch_tr',
            name='condition_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_EXT_CND_TR'),
        ),
        migrations.AddField(
            model_name='t_ext_cnd_ch_tr',
            name='conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_CONDITIONS_MS'),
        ),
        migrations.AddField(
            model_name='t_ext_cnd_ch_tr',
            name='target0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_TRG_PRM_MS'),
        ),
        migrations.AddField(
            model_name='t_ext_cnd_ch_tr',
            name='target1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_STATISTIC_MS'),
        ),
        migrations.AddField(
            model_name='t_ext_cnd_ch_tr',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_UNIT_MS'),
        ),
        migrations.AddField(
            model_name='t_bland_ms',
            name='industry_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_INDUSTRY_MS'),
        ),
        migrations.AddField(
            model_name='t_bland_ms',
            name='scale_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_SCALE_MS'),
        ),
    ]
