# Generated by Django 2.1.3 on 2018-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_URL_MS',
            fields=[
                ('url_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('url_str', models.CharField(max_length=128)),
                ('tag_cd', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('get_flg', models.IntegerField()),
            ],
        ),
    ]
