# Generated by Django 2.1.3 on 2018-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_t_url_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_stk_prc_tr',
            name='day_before_ratio',
            field=models.FloatField(),
        ),
    ]
