# Generated by Django 2.1.1 on 2018-09-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_auto_20180927_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_EXT_CND_CH_TR',
            fields=[
                ('condition_ch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('condition_type', models.CharField(max_length=256)),
                ('threshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_EXT_CND_TR')),
                ('target0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_TRG_PRM_MS')),
                ('target1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_STATISTIC_MS')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.T_UNIT_MS')),
            ],
        ),
    ]
