# Generated by Django 2.1.1 on 2018-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_auto_20180928_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_CONDITIONS_MS',
            fields=[
                ('conditions_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('conditions_name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
