# Generated by Django 2.1.1 on 2018-09-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_t_conditions_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ext_cnd_ch_tr',
            name='conditions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='investment.T_CONDITIONS_MS'),
            preserve_default=False,
        ),
    ]
