SELECT
    T_BLAND_MS.BLAND_CD,
    T_BLAND_MS.BLAND_NAME,
    T_BLAND_MS.MARKET_PROD_CLS,
    T_BLAND_MS.INDUSTRY_CD,
    T_INDUSTRY_MS.INDUSTRY_NAME,
    T_BLAND_MS.SUB_INDUSTRY_CD,
    T_SUB_INDUSTRY_MS.INDUSTRY_NAME,
    T_BLAND_MS.SCALE_CD,
    T_SCALE_MS.SCALE_NAME
FROM   
    T_BLAND_MS
LEFT OUTER JOIN T_INDUSTRY_MS
    ON T_INDUSTRY_MS.INDUSTRY_CD = T_BLAND_MS.INDUSTRY_CD
LEFT OUTER JOIN T_INDUSTRY_MS AS T_SUB_INDUSTRY_MS
    ON T_SUB_INDUSTRY_MS.INDUSTRY_CD = T_BLAND_MS.SUB_INDUSTRY_CD
LEFT OUTER JOIN T_SCALE_MS
    ON T_SCALE_MS.SCALE_CD = T_BLAND_MS.SCALE_CD
WHERE
    T_BLAND_MS.FETCH_FLG = 0
;
